version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - "80:80"
    depends_on:
      - maria_db
    links:
      - maria_db:app_db
  maria_db:
    image: "mariadb:latest"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: YOUR_DB
      MYSQL_USER: YOUR_USERNAME
      MYSQL_PASSWORD: YOUR_PASSWORD
      MYSQL_ROOT_PASSWORD: YOUR_PASSWORD